# -*- mode: ruby -*-
# vi: set ft=ruby :
require "yaml"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	box_props = YAML.load_file("box.properties")
	aws_props = YAML.load_file("aws.properties")

	config.vm.box = "#{box_props['box']['name']}"
	config.vm.box_url = "file://#{box_props['box']['base_location']}"

	config.vm.provider :aws do |aws, override|
		aws.access_key_id = "#{aws_props['keys']['access_key_id']}"
		aws.secret_access_key = "#{aws_props['keys']['secret_access_key']}"
		aws.keypair_name = "jeqo"

		aws.instance_type = "m3.medium"
		aws.region = "sa-east-1"
		aws.availability_zone = "sa-east-1a"
		aws.ami = "ami-0511a418"
		#aws.elastic_ip = "54.94.207.207"

		override.ssh.username = "ec2-user"
		override.ssh.private_key_path = "#{aws_props['keys']['key_pair_location']}"

		aws.tags = {
		  'Name' => box_props['box']['name']
		}

		aws.block_device_mapping = [{
			'DeviceName' => '/dev/sda1',
			'Ebs.VolumeSize' => box_props['box']['disk_size']
		}]

		aws.security_groups = "jeqo-group"

		config.ssh.pty = true
	end

	config.omnibus.chef_version = :latest

	config.vm.provision "shell" do |s|
		s.path	= "increase_swap.sh"
		s.args   = "'#{box_props['box']['additional_swap']}'"
	end

	config.vm.provision "chef_client" do |chef|
		chef.chef_server_url = "https://api.opscode.com/organizations/jeqo"
		chef.validation_client_name = "jeqo-validator"
		chef.validation_key_path = "#{box_props['chef']['repo_location']}/.chef/jeqo-validator.pem"
		chef.node_name = "#{box_props['box']['name']}"
		chef.add_role "nfs-client"
		chef.add_role "oracle_db-xe"
		chef.add_role "demo-bpm_bam-12c"
		chef.json = {
			"nfs-client" => {
				"server-host" => "172.31.18.67"
			},
			"oracle-xe" => {
				"url" => "file:///data/oracle-xe/oracle-xe-11.2.0-1.0.x86_64.rpm"
			},
			"bpm_qs-12c" => {
				"url" => "file:///data/oracle-fmw/bpm_qs-12c/fmw_12.1.3.0.0_bpmqs_Disk1_1of1.zip"
			}
		}
	end
end
